// SPDX-License-Identifier: AGPL-3.0-only
export * from "./manifest.js";
export * from "./host.js";
export { collect, DETECTORS, type CollectOptions } from "./collect.js";
export { nodeHost, spawnRun } from "./live-host.js";
export { firstLine } from "./detect/common.js";
export type { Detector } from "./detect/common.js";
export { detectIdentity } from "./detect/identity.js";
export { detectShell } from "./detect/shell.js";
export { bareSources, guardSources, shellSources } from "./detect/sources.js";
export { GUARD_BEGIN, GUARD_END, calledCommands, dropPlugins, guardCommands } from "./detect/commands.js";
export { TERMINAL_FONT_ID, alacrittyFont, detectTerminalFont, ghosttyFont, itermFont, kittyFont, weztermFont } from "./detect/terminal.js";
export { GHOSTTY_BUILT_IN_FONT, ghosttyConfigPaths, parseGhosttyDirectives, readGhosttyConfig, themeFor, type GhosttyDirective } from "./ghostty-config.js";
export { detectToolchains } from "./detect/toolchains.js";
export { aptPackages, aptSizes, parseAptManual, parseDpkgFields } from "./detect/apt.js";
export { detectTools, jsGlobalFolders, packageCommands, parseBrewfile, parseBunGlobals, parseCargoInstalls, parseGoVersionM, parseNpmGlobals, parsePipxList, parsePnpmGlobals, parseUvToolList, type BrewLine, type GoModule, type Pkg } from "./detect/tools.js";
export { classifyFormulae, linuxSupport, renderSnapshot, type BottleSnapshot } from "./brew-bottles.js";
export { LINUX_BOTTLES } from "./data/linux-bottles.js";
export { AGENTS, agentRowId, detectAgents } from "./detect/agents.js";
export { type Presence, presenceOf } from "./detect/presence.js";
export * from "./history/index.js";
export { type CommandCount, type RecipeOptions, computeRecipe, floorApplies, unknownCommands, withProject } from "./recipe.js";
export { PROJECT_READERS, type ProjectNeed, type ProjectScan, scanProject } from "./project/index.js";
export type { ProjectFile, ProjectFinding, ProjectReader } from "./project/reader.js";
export { MCP_BIN_DIRS, MCP_REMOTE_ID, MCP_REMOTE_LABEL, detectMcp, homePaths, linuxFit, mcpRemoteHash, secretNamed, stdioLine, type LinuxFit } from "./detect/mcp.js";
export { SWITCHED_OFF_HERE, detectProjectMcp, outsideProjectLine, type ProjectServer } from "./detect/mcp-project.js";
export { readCheckout, readTurnServers } from "./detect/turn-servers.js";
export { detectPlugins, pluginIo, pluginRow, type AgentPlugins, type PluginsRead } from "./detect/plugins.js";
export { SKILL_HEAD_BYTES, SKILL_LINK_ABOVE, detectSkills, skillFrontmatter, skillMdFrontmatter, skillRoots, type SkillRootAt, type SkillsRead } from "./detect/skills.js";
export { CLAUDE_KEY_ENV, apiKeyHelperOf, billedHere, claudeBills, detectLogins } from "./detect/logins.js";
export { FISH_CONF_D, RC_NAMES, RC_PATHS, isRcPath, isSecretName, rcFiles, simpleCommands, sourcedPaths, stripExports } from "./detect/shell-rc.js";
export { type Signal, MAX_BYTES, bareUrls, fileSignals, keysSignal, modeSignal, nameSignal, pemSignal, topLevelKeys, urlSignal } from "./credential-signals.js";
export { CACHE_DIRS, FINDER_METADATA } from "./cache-names.js";
export { seedMenu } from "./seed.js";
export { SSH_CONFIG_PATH, SSH_IGNORE_UNKNOWN_DETAIL, withIgnoreUnknown } from "./ssh-config.js";
